#!/usr/bin/env bash

source "$HOME/.config/sketchybar/scripts/colors.sh"
source "$HOME/.config/sketchybar/scripts/icons.sh"

ITEM_DIR="$HOME/.config/sketchybar/items"
PLUGIN_DIR="$HOME/.config/sketchybar/plugins"

FONT="JetBrainsMono Nerd Font"

ICON_SIZE=9.0
LABEL_SIZE=10.0

PADDINGS=3
SEGMENT_SPACING=13

CORNER_RADIUS=5

POPUP_BORDER_WIDTH=2
POPUP_CORNER_RADIUS=11

SPACE_CLICK_SCRIPT="yabai -m space --focus \$SID 2>/dev/null" # The script that is run for clicking on space components

SHADOW=on

# Bar Appearance
sketchybar --bar color=$BAR_COLOR                                       \
                 height=20                                              \
                 shadow=$SHADOW                                         \
                 position=top                                           \
                 sticky=on                                              \
                 padding_left=10                                        \
                 padding_right=$((10 - $PADDINGS))                      \
                 corner_radius=10                                       \
                 y_offset=0                                             \
                 margin=0                                               \
                 blur_radius=80                                         \
                 notch_width=0                                          \
                 border_color=$BAR_COLOR                                \
                 border_width=0                                         \
                 notch_offset=0                                         \
                 display=all                                            \
                 hidden=off                                             \
                 topmost=off                                            \
                 font_smoothing=on                                      \

# Changing Defaults
sketchybar --default updates=when_shown                                 \
                     icon.font="$FONT:Bold:$ICON_SIZE"                  \
                     icon.color=$ICON_COLOR                             \
                     icon.padding_left=$PADDINGS                        \
                     icon.padding_right=$PADDINGS                       \
                     label.font="$FONT:Bold:$LABEL_SIZE"                \
                     label.color=$LABEL_COLOR                           \
                     label.padding_left=$PADDINGS                       \
                     label.padding_right=$PADDINGS                      \
                     background.padding_left=$PADDINGS                  \
                     background.padding_right=$PADDINGS                 \
                     popup.background.border_width=2                    \
                     popup.background.corner_radius=11                  \
                     popup.background.border_color=$POPUP_BORDER_COLOR  \
                     popup.background.color=$POPUP_BACKGROUND_COLOR     \
                     popup.background.shadow.drawing=$SHADOW            \
                     drawing=on

# Left
source "$ITEM_DIR/skhdmod.sh"
source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/front_app.sh"

# Right
source "$ITEM_DIR/power.sh"
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/macbar.sh"

##### Finalizing Setup #####
sketchybar --update

echo "sketchybar configuration loaded.."
