#!/usr/bin/env sh

# Yabai Icons
# YABAI_STACK=stack
# YABAI_FULLSCREEN_ZOOM=full
# YABAI_PARENT_ZOOM=Z
# YABAI_FLOAT=float
# YABAI_GRID=tall

YABAI_STACK=S
YABAI_FULLSCREEN_ZOOM=F
YABAI_PARENT_ZOOM=Z
YABAI_FLOAT=f
YABAI_GRID=B
